<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<style>
    @media (min-width: 1025px) {
        .h-custom {
            height: 100vh !important;
        }
    }
</style>

<body>

    <section class="h-100 h-custom">
        <div class="container py-5 h-100">
            <!-- <div>
                <form action="/adduser">
                    <select onchange="this.form.submit()" name="locale">
                        <option value="english">Choose Language</option>
                        <option value="english">English</option>
                        <option value="german">German</option>
                        <option value="hindi">Hindi</option>
                    </select>
                </form>
                <?php
                if (isset($_GET['locale'])) {
                    echo 'Language is set to ' . $_GET['locale'];
                }
                ?>
            </div> -->
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">

                    <h3 class="mb-4 pb-2 pb-md-0 mb-md-3 px-md-2 float-center"><?php echo $this->locale->_('Admin Login'); ?></h3>
                    <form class="px-md-2" method="post" action="">

                        <div class="form-floating mb-3">
                            <input name="email" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                            <label for="floatingInput"><?php echo $this->locale->_('Email Address'); ?></label>
                        </div>

                       
                        <div class="form-floating mb-3">
                            <input name="password" type="password" class="form-control" id="floatingInput" placeholder="Password">
                            <label for="floatingInput"><?php echo $this->locale->_('Password'); ?></label>
                        </div>
                        
                        <span class="text text-<?php echo $success === true ? 'success' : 'danger'; ?>">
                            <?php if ($msg) {
                                echo $msg;
                            }
                            ?>
                        </span>
                     


                        <input type="submit" value="<?php echo $this->locale->_('Login'); ?>" class="btn btn-success btn-lg mb-1">
                </div>
                </form>
                

            </div>
        </div>
        </div>
        </div>
    </section>
</body>

</html>